### ISSUE TITLE
client.get_counters: Yajl::ParseError  lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by pwmpw** [igor-alexandrov/metrika#5]
method: @client.get_counters

```
A Yajl::ParseError occurred in some_controller#new:

  lexical error: invalid char in json text.
                                       <?xml version='1.0' encoding='U
                     (right here) ------^
```

**Comment by tikijian** [comment]
+1 
по умолчанию яндекс отдает XML в старой версии API. чтобы получить JSON надо передать Content-type: application/json

**Comment by pwmpw** [comment]
https://github.com/igor-alexandrov/metrika/blob/master/lib/metrika/helpers/request.rb#L4-L9
передаются такие:

```
'Accept' => 'application/x-yametrika+json',
'Content-Type' => 'application/x-yametrika+json'
```

надо что бы автор пулл реквесты заапрувил, там уже фиксы есть.

**Comment by tikijian** [comment]
@clevertechru 
у автора ссылка внутри гема неактуальная.
сейчас там такая 

``` ruby
client.instance_eval { response = get('https://api-metrika.yandex.ru/counters'); puts response}
```

выдает XML и нашу ошибку.

если поменять на новую версю АПИ

``` ruby
client.instance_eval { response = get('https://api-metrika.yandex.ru/management/v1/counters'); puts response}
```

вернет JSON

Но по идее 'Content-Type' => 'application/x-yametrika+json' должен работать с первой версией. Может у автора этот заголовок в итоге не отправляется? Не получается проверить

**Comment by tikijian** [comment]
еще такой вариант работает с первой версией

``` ruby
client.instance_eval { response = get('https://api-metrika.yandex.ru/counters.json') }
```

**Comment by pwmpw** [comment]
Заголовки отправляются, смотрел TCP  дампом. На всякий случай кинул письмо в поддержку яндекса, а так уже понятно в чем дело, тикет закрываю.
